package ru.eremenko.demo.repo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

public class WorkWithDb {

    private final Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost/ctable", "postgres", "root");
    private final Statement stmt = connection.createStatement();


    public WorkWithDb() throws SQLException {
    }

    public void createTable() {
        try {
            stmt.executeUpdate("CREATE TABLE public.usr\n" +
                    "(\n" +
                    "    id bigint GENERATED BY DEFAULT AS IDENTITY,\n" +
                    "    name character(255) NOT NULL,\n" +
                    "    birthday date NOT NULL,\n" +
                    "    gender character(255) NOT NULL,\n" +
                    "    PRIMARY KEY (id)\n" +
                    ");\n" +
                    "\n" +
                    "ALTER TABLE public.usr\n" +
                    "    OWNER to postgres;");
        } catch (SQLException throwables) {

        }
        System.out.println("Создал таблицу");
    }

    public void createUser(String name,String birthday,String gender) throws SQLException {
        stmt.executeUpdate("insert into usr (name, birthday, gender) values (\'"+name+"\',\'"+birthday+"\',\'"+gender+"\')");
    }

    public ArrayList<String[]> getUniq() throws SQLException {
        ArrayList<String[]> uniqUsers = new ArrayList();
        ResultSet uniq = stmt.executeQuery("select distinct name,birthday from usr order by name");

       while(uniq.next()){
           ResultSet usr = stmt.executeQuery("select name,birthday,gender from usr where usr.name=\'"+uniq.getString(1)+"\' and usr.birthday=\'"+uniq.getString(2)+"\'");
           if(usr.next()){
               uniqUsers.add(new String[]{usr.getString(1),usr.getString(2),usr.getString(3)});
           }

       }
        return uniqUsers;
    }

    public void getStartWithF() throws SQLException {
        long time = System.currentTimeMillis();
        stmt.executeUpdate("select * from usr where name like 'F%' and gender like 'm%'");
        System.out.println("Время в миллисекундах: "+(System.currentTimeMillis() - time));
    }
}
